### ISSUE TITLE
feat: add syntax highlighting for the github unfurl integration

### ISSUE THREAD

**Issue by bguiz** [GitbookIO/integrations#178]
## What

- Add an additional parameter to the github-unfurl integration to specify the syntax highlight language
  - This is optional, and if not specified, will default to a language inferred from the file extension where present, and default to no highlighting when no file extension is present
- Add an additional parameter to the github-unfurl integration to specify the syntax highlight theme
  - This is optional, and if not specified, will default to the syntax highlight theme that is default for the current gitbook theme

## Why

Satisfy the following user stories:

- As a technical documenter, I would like to migrate existing code examples from inline (within markdown code blocks) to reference the same code within a github repo, and have it look the same as before.
- As a developer reading technical documentation, I would like to see syntax highlighting so that I can mentally parse the code shown in the tutorial/ article more intuitively.

## Refs

- https://github.com/GitbookIO/integrations/pull/151

**Comment by addisonschultz** [comment]
Hey @bguiz, I've made some updates that should be now published and available ツ 

https://github.com/GitbookIO/integrations/pull/194

I've tested them both quite a bit, but please let me know if there's anything else I missed!
