### ISSUE TITLE
Sync with gitlab/github project's wiki repository

### ISSUE THREAD

**Issue by cesarizu-incine** [GitbookIO/integrations#447]
There seems to be no way to sync with a gitlab/github project's wiki. The repository for the wiki is not the same as the main repository. The url is the same but with `.wiki.git` instead of `.git`. This applies to both github and gitlab.

See:
* https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#cloning-wikis-to-your-computer
* https://docs.gitlab.com/ee/user/project/wiki/#create-or-edit-wiki-pages-locally

Is there a way to sync with the wiki repository of a project instead of the main repository?

**Comment by addisonschultz** [comment]
Hi @cesarizu-incine - good question. Do you have an example of a public wiki I could look into? We offer the option to sync with monorepos: https://docs.gitbook.com/integrations/git-sync/monorepos

I'm wondering if setting the monorepo directory to the wiki path would work?

**Comment by cesarizu-incine** [comment]
There are a lot of examples for GitHub here (GitLab works the exact same way): https://github.com/MyHoneyBadger/awesome-github-wiki?tab=readme-ov-file#examples

Just one example from that list:

- Main Repo: https://github.com/facebook/react-native.git
- Wiki Repo: https://github.com/facebook/react-native.wiki.git

It is a different repository, so using the monorepo directory wouldn't work.

**Comment by addisonschultz** [comment]
Hi @cesarizu-incine - I see now, it's a good feature request. I've moved it to our community, where this feature request would fit better! Feel free to leave more context there for us to check out. 

https://github.com/orgs/GitbookIO/discussions/583

Thanks again for filing, I'm going to close this feature request in this repository for now.

**Comment by addisonschultz** [comment]
Hey @cesarizu-incine - just wanted to update: You can actually import a GitHub Wiki into GitBook!

https://docs.gitbook.com/content-editor/import

Hope that helps!
