### ISSUE TITLE
Feature request: Extend fathom integration to track external links

### ISSUE THREAD

**Issue by KevinRohn** [GitbookIO/integrations#450]
# Description

We use the [Fathom integration](https://github.com/usefathom) for analytics on our GitBook pages. Currently, the functionality is limited to tracking only internal site links. However, Fathom also offers an "events" feature, which could be useful for tracking external link clicks.

I attempted to create an integration myself, but it requires script injection. Unfortunately, this functionality is not supported for private integrations.

It would be beneficial to support tracking events for external links. For more information, see [Fathom's documentation on events](https://usefathom.com/docs/features/events).

Thank you in advance

**Comment by addisonschultz** [comment]
Hi @KevinRohn! Great feature request, and even nicer that you've already tried to build an integration for this. You are right in that we don't allow the script injection scope to be published, but if you would be interested in opening up a PR in this repo that would update the [current Fathom integration](https://github.com/GitbookIO/integrations/tree/main/integrations/fathom), I'd be happy to review and test, and update the current integration if it's working well. 

Let me know if that sounds interesting to you, and we can work on it!t

**Comment by KevinRohn** [comment]
Hi @addisonschultz, I would like to do this, but how can I test it before if I can not inject a script?

Should it work with executing `gitbook dev <spaceID>` ?

**Comment by KevinRohn** [comment]
Hi @addisonschultz,

sorry, rather later than never :) . I opened an PR https://github.com/GitbookIO/integrations/pull/534

**Comment by addisonschultz** [comment]
Closing as PR was merged 🙌
